### ISSUE TITLE
支持双usb摄像头吗

### ISSUE THREAD

**Issue by jp1017** [rockcarry/v4l2test#6]
:smile: :+1:

**Comment by rockcarry** [comment]
多少个都可以，关键是硬件支持不，还有如何编码
软件编码基本上是不可能应用到产品去的

**Comment by jp1017** [comment]
@rockcarry 我现在通过hub连了两个usb摄像头,同时打开,一个会报带宽不足的错误导致黑屏,会是系统的问题吗?

**Comment by rockcarry** [comment]
只开一个是否正常？
摄像头分辨率，帧率，像素格式是多少？
错误 log 发来看下。
如果是带宽问题，可以考虑用 jpeg 格式的，这样数据量会小些。

**Comment by jp1017** [comment]
我用这个库: https://github.com/saki4510t/UVCCamera/ 没有使用v4l2

你这个库怎么编译成apk呢,release里的应用打开崩溃,,,

**Comment by rockcarry** [comment]
apk 在另外一个项目里面 CameraDVR

**Comment by rockcarry** [comment]
v4l2test 可以在命令行运行，可以测试下是否正常
