### ISSUE TITLE
How to detect lost connection from Camera?

### ISSUE THREAD

**Issue by Rainbow87** [rockcarry/v4l2test#7]
Hi CK,
in CameraDVR app, does any way to detect lost connection from camera? eg. i use CVBS camera, when unplug camera, the preview window is blue color, i want to detect lost connection and show notice message "Video Loss".

Thanks!

**Comment by rockcarry** [comment]
if usb unplug, the /dev/videox will be disappear, this is a way to detect.
another way to check the data receiving error or timeout or not.


    while (!(cam->thread_state & CAMDEV_TS_EXIT)) {
        FD_ZERO(&fds);
        FD_SET (cam->fd, &fds);
        tv.tv_sec  = 1;
        tv.tv_usec = 0;
        if (select(cam->fd + 1, &fds, NULL, NULL, &tv) <= 0) {
            ALOGD("select error or timeout !\n");
            continue;
        }

check these code, and check log "select error or timeout !"
if this log printed, you can notify the app to display messages.

**Comment by Rainbow87** [comment]
Hi Ck,
on DVRCamera app, we can detect image frame in this function:
public void onSurfaceTextureUpdated(SurfaceTexture texture) {
            // Invoked every time there's a new Camera preview frame
            mainCAMFrame++;
}

so, we can detect lost camera signal.
