### ISSUE TITLE
ffmpeg问题

### ISSUE THREAD

**Issue by lwn920917** [rockcarry/v4l2test#9]
我执行：./build_ffmpeg_for_android.sh
Cloning into 'x264'...
remote: Counting objects: 21253, done.
remote: Compressing objects: 100% (4652/4652), done.
remote: Total 21253 (delta 17598), reused 20107 (delta 16558)
Receiving objects:  99% (21084/21253), 5.00 MiB | 3.00 KiB/s 

一直不动，不知道为什么，您能帮助解答一下吗？

**Comment by rockcarry** [comment]
这个是在 clone x264 的代码，你 clone 不下来，我也没办法啊。
